<a href="https://colab.research.google.com/github/naijacoderorg/lectures/blob/main/Python_Puzzles_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a name='gettingStarted'></a>
# 1) üöÄ Getting started

<!--- [Outline](https://docs.google.com/document/d/1_xT-ZEcWeHVXGthJDkCHTDhhPdMzcVC3DU2_S3amy-0/edit?usp=sharing)
--->

<h2>Learn Python with puzzles</h2>


Immerse yourself in Python through a series of puzzles. If you like to figure things out on your own, this is perfect for you! We think puzzles are useful because coding involves lots of problem solving. If you prefer a traditional lecture-based class, try [Python for Everyone](https://www.py4e.com/lessons).

Python is a simple but powerful programming language that reads almost like English. This *colab notebook* is how we will be teaching you to code. Colab notebooks are often used for analyzing data, so colab is useful to know. It's also the easiest way to run python because it doesn't require installing anything. Notebooks are saved in your google drive for you to come back and review. Python is great for AI and data analysis. If what you want to do is make interactive games, try learning [scratch](https://scratch.mit.edu). If you want to make interactive web pages, learn [javascript](https://www.w3schools.com/js/) and [html](https://www.w3schools.com/html/).

<h2>üìî Notebook Structure</h2>

This notebook is divided into short sections each teaching concepts through three kinds of puzzles:

* üìñ `learn`: teach you the concepts step by step **(optional)**
* üèÜ `challenge`: test your understanding of the concept taught in the section
* üèÖ `extra_credit`: fun harder problems **(optional)**
<!-- comment: *   `extra_practice`: optional puzzles for those looking for more practice -->

üëâ **Tip**: *Feel free to skip* ‚è© *the `learn` puzzles if you are already familiar with programming or feel you don't need them.*

**License/copyright**: see the [license](#license) section.

**Help out:** email [wespeakpython@gmail.com](mailto:wespeakpython@gmail.com) to contribute suggestions, corrections, new puzzle ideas, or other feedback. This notebook was created by Maya and Adam Kalai. We are new to teaching and would love to collaborate with teachers/tutors! üôè

<h2> üñ® Cells and printing</h2>
Notebooks are divided into cells that make it easy to run a little bit of code at a time, which makes it easy to debug (fix mistakes).

In [ ]:
# This is a comment. Python ignores things after a hash #
# Press the play button on the left or Control-Enter to "run" this cell
1 + 1

üëâ **Tip:** Good learning strategies are to: (a) guess what will happen before you run a cell, and (b) try to understand what actually happened, and (c) make your own cells and try things out.

In [ ]:
1+1

In [ ]:
x = 1  # this is how you make a variable and set it's value
# use print to help see what's going on
# print(x)
y = x + 1
# print(y)
z = x + y
# print(z)
if True:
  print('hello')

**Tip: Make your own cells, try things out**

You will need to make your own cells to solve puzzles. But you will also need to create cells to try things out. Feel free to explore any curiosity you have. Try making a new code cell with something you are curious about and run it. Errors are great learning opportunities, and there will be no shortage of those in learning to program üòÜ.

In [ ]:
print('Make a new cell below this one, put something inside of it, and run it')
# To make a new code cell, move your mouse just to the bottom edge of the cell
# and press the `+ Code` button that magically appears there.
# This can also be done by pressing `Escape` followed by `b`

![Illustration of creating a new cell by clicking]()

If you want to learn more about cells and colab notebooks, follow [this tutorial notebook](https://colab.research.google.com/notebooks/intro.ipynb) or watch [this video](https://www.youtube.com/watch?v=inN8seMm7UI).

<h2>üß© Puzzles</h2>

A puzzle is what is refered to in python as a function. A function is something that takes a input (something you put in) and returns an output (something that is returned). To solve a puzzle you need to find a input that will make the puzzle return `True`.

In [ ]:
# Run this cell
# First, the puzzle is defined
# def stands for define
# sat is for the SATISFACTION you feel when you SATISFY the function

def sat(x: str):
  return 'Hello, ' + x == 'Hello, world!'

# Then, solve it
sat('world!')

`True` that means the solution is correct!

In [ ]:
# Run this next

def sat(x: int):
  return x + x == 2

sat(7)  # Then fix the input 7 to the right number and re-run

`False` means it was not yet solved. Next try to change the 7 above to a number that makes the puzzle return `True`
and re-run the cell
</details>

If it says `True` You just solved your first puzzle! `sat` is short for **satisfy**. Isn't it satisfying?**

In [ ]:
def sat(x: int): # :int is a "type hint" meaning x should be an integer number
  return x + x == 4

# From now on, you will need to make your own cells to solve puzzles.
sat(íäπ)  # replace the íäπ with your answer

<details><summary>Answer</summary>

```python
sat(2)
```

</details>

<h2>üß≠ Navigating the notebook</h2>

Click on the table of contents on the left to navigate to different areas of the notebook.
You can collapse a whole section once you've completed it by clicking on the black triangle.
Try collapsing this section or the whole *Getting started* section.

In [ ]:
if 0: íäπ = 3 # Ignore this cell. (It prevents red squigglies on all the íäπ)

# 2) üî¢ Numbers

You will see `def sat(n: int)` in each of the puzzles below. The **`int`** is called a **type hint** and means that the answer should be an integer, a number with no decimal point.

In [ ]:
# You may skip ahead once you think you're ready for the challenges

def sat(n: int):
  return n + 3 == 8

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(5)
```

</details>

In [ ]:
def sat(n: int):
  m = n - 10
  return m == 20

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(30)
```

</details>

In [ ]:
def sat(n: int):
  print("print statements can help you understand what's going on")
  print('you will also learn how to use a debugger, which is even better')
  print('your input: n =', n)
  a = n + 1
  print('            a =', a)
  b = a - n
  print('            b =', b)
  c = a - b
  print('            c =', c)
  return c == 5

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(5)
```

</details>

In [ ]:
17 * 4325 # run this cell. You can use Python as a calculator

In [ ]:
12345 * 54321

670592745

In [ ]:
def sat(n: int):
  return n == 12345 * 54321  # Hint: use python to solve this, not a pencil

sat(12345 * 54321)

True

<details><summary>Hint</summary>

**Option 1:** Make a new cell by pressing on `+ Code` (see [Section 1](#gettingStarted)) and  run `print(12345 * 54321)` in that cell and copy/paste the answer.

<details><summary>Answer</summary>

```python
sat(670592745)  # we got this by running print(12345 * 54321) in a cell
```
</details>

**Option 2:** Put you solution directly inside the parentheses `sat(? * ?)`

<details><summary>Answer</summary>


```python
sat(12345 * 54321)  # we got this by running print(12345 * 54321) in a cell
```

</details>

There are many ways to skin a python.



</details>

üß™ **Experiment**
Programming requires figuring things out. Try things out in code cells or search the web. It may be hard at first, but figuring things out is a skill you will develop. You can always look at our answers, but first try things out.

In [ ]:
pow(5, 2)

25

In [ ]:
def sat(n: int):
  return n == pow(5, 2)

# pow is a "function" built in to Python.
# It takes two numbers as input and returns a number.
# What does it do?
# Run the cell below and try to figure it out!

sat(pow(5, 2))


<details><summary>Answer</summary>

`pow(a, b)` $ = a^b$, a to the power of b (also called an exponent)

<details><summary>Answer</summary>

```python
sat(25)
```
or
```python
sat(pow(5, 2))  # this is not cheating
```
</details>
</details>

In [ ]:
# Doing experiments like this can help you figure out how things work
# Searching the web is also great
# Useful sites include w3schools.com and stackoverflow.com

print("Experiment: pow(2, 1) =", pow(2, 1))
print("Experiment: pow(2, 2) =", pow(2, 2))
print("Experiment: pow(2, 3) =", pow(2, 3))
print("Experiment: pow(-1, 3) =", pow(-1, 3))
print("Experiment: pow(3, -1) =", pow(3, -1))

üëâ Remember the **pow**er of experiments üß™

In [ ]:
# Experiment to figure out what != means
def sat(n: int):
  return n != 5

sat(íäπ)

<details><summary>Hint</summary>

`!=` means NOT equal to, so there are many answers!!!

<details><summary>Answer</summary>

```python
sat(17)
````
</details>

</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  foo = n + 1
  bar = foo + 3
  return foo == 6

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(5)
```

</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  return n > 101  # figure out what > means

sat(íäπ)

<details><summary>Hint</summary>

`>` means greater than, so there are many answers!!!

<details><summary>Answer</summary>

```python
sat(83293742983479202023)
````
</details>

</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  return n / 241356987 == 100000000  # Tip: copy/paste avoids typos

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(24135698700000000)
```

</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  return n == pow(12345, 6789)

sat(íäπ)

<details><summary>Answer <b>without copying a million digits</b></summary>

You could `print` and then copy/paste the answer. However, Python can do the work for you.

```python
n = pow(1234, 56789)
sat(n)
```

OR

```python
sat(pow(1234, 56789))
```

</details>

In [ ]:
###########################################################
#                      EXTRA CREDIT                       #
###########################################################

def sat(n: int):
  print('n =', n, 'and n * n =', n * n)
  return n * n == 123454321

sat(íäπ)

<details><summary>Sneaky hint</summary>

`pow(123454321, ?)` with what value of `?` computes square root.

<details><summary>Answer</summary>


```python
sat(11111)
```
</details>
</details>

In this section, you have learned about `int` arithmetic and basic comparisons.

**Decimals:** The next notebook has `float` puzzles that involve decimals.

Read [more about Python numbers](https://www.w3schools.com/python/python_numbers.asp) at W3Schools.

# 3) üß∂ Strings

A string is any sequence of characters (letters, digits, spaces, punctuation, etc.) that's inside quotes `'like this'` or `"like this"`

‚ûï *Concatenate* strings using `+` which glues them together

In [ ]:
# You may skip ahead once you think you're ready for the challenges

def sat(word: str):  # ": str" is a type of hint that the answer is a string
  sentence = 'Python is ' + word
  return sentence == 'Python is fun'

sat(íäπ)

<details><summary>Hint</summary>

Make sure your answer is in `'quotes'`.

<details><summary>Answer</summary>

```python
sat('fun')
```
</details>

</details>

In [ ]:
def sat(word: str):
  sentence = 'Python is ' + word
  return sentence == 'Python is fun'  # Python is very picky!

sat(íäπ)

<details><summary>Hint</summary>
The difference between this and the last puzzle is a space after the wrod `is` in `'python is'`.

<details><summary>Answer</summary>

```python
sat(' fun')
```
</details>
</details>

In [ ]:
def sat(so_fun: str):
  motto = 'Python is ' + so_fun
  return motto == 'Python is FUN'

sat(íäπ)

<details><summary>Hint</summary>

The string you create should be EXACTLY the same as the one in the function, CAPITALIZATION matters!!!

<details><summary>Answer</summary>

```python
sat('FUN')
```
</details>
</details>

In [ ]:
def sat(s: str):
  return ':' + s == ':)'

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(')')
```
</details>

In [ ]:
def sat(s: str):
  happy = s + ''
  return happy == ':)'

sat(íäπ)

<details><summary>Hint</summary>

Make sure your answer is formated correctly. Note that there is a difference between returning `False` and returning a error. False means your answer does not satisfy what the function is checking, error means that python cannot do something you are asking it to. Think about what would happen if you replaced you answer with `x` in the function.

<details><summary>Answer</summary>
```python
sat(':)')
```
</details>

</details>

In [ ]:
def sat(i: str):
  return i + 'yes' == 'eyes'

sat(íäπ)

<details><summary>Answer</summary>

```python
sat('e')
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(s: str):
  return s + s == '2222'

sat(íäπ)

<details><summary>Answer</summary>

```python
sat('2')
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: str):
  return n + '0' == '0'

sat(íäπ)

<details><summary>Hint</summary>

Look for the answer inside the happy learn puzzle above :)

<details><summary>Answer</summary>

```python
sat('')
```
</details>
</details>

In [ ]:
###########################################################
#                      EXTRA CREDIT                       #
###########################################################

def sat(s: str):
  return s + 'worry' == "Don't worry"

# You can use 'single' or "double" quotes for strings

sat(íäπ)

<details><summary>Answer</summary>

```python
sat("Don't ")
```
</details>

In [ ]:
def sat(n: int):
  return len('How long is this string?') == n

sat(íäπ)

<details><summary>Answer</summary>

```python
n = len('How long is this string?')
sat(n)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  return len('seven') == n

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(5)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(s: str):
  return len(s + 'bar' + s) < 4

sat(íäπ)

<details><summary>Answer</summary>

```python
sat('')
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(s: str):
  return 'A rose by any other name would smell' in s  # what does "in" do?

sat(íäπ)

<details><summary>Answers</summary>

```python
sat('A rose by any other name would smell as sweet. --William Shakespeare')
```

OR

```python
sat('A rose by any other name would smell')
```


</details>

In [ ]:
######################## CHALLENGE ########################

def sat(s: str):
  return ("g" + s + 't') in 'Bigfoot'

sat(íäπ)

<details><summary>Answers</summary>

```python
sat('foo')
```

OR

```python
sat('A rose by any other name would smell')
```


</details>

In this section, you've learned about strings, how to add/concatenate them, how to find out their length, and how to test if one string is a substring of another.

If you want, read more about strings at [CS circles](https://cscircles.cemc.uwaterloo.ca/3-comments-literals/) or [W3Schools](https://www.w3schools.com/python/python_strings.asp).

# 4) üëª *Boo*leans: `True` `and` `False`?

In [ ]:
def sat(s: str):
  return s == 'cat' or s == 'dog' or s == 'unicorn'

sat(íäπ)  # which kind of person are you?

<details><summary>Answer</summary>

```python
sat('unicorn')  # correct answer!
```
</details>

In [ ]:
def sat(n: int):
  return n * n == -1 or 4 + n == 8

sat(íäπ)

<details><summary>Answer<b>s</b> &nbsp;&nbsp;&nbsp;</summary>

```python
sat(4)
```

OR Python also has [Complex numbers](https://www.tutorialspoint.com/complex-numbers-in-python") if you want to solve it the hard way.

```python
sat(1j)  
```

</details>

In [ ]:
def sat(i: int):
  return i == 5 or i != 5

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(31415926535)
```
</details>

In [ ]:
def sat(n: int):
  a = (n > 5)  # a is going to be True or False
  b = (n < 9)  # b is going to be True or False
  c = a and b  # c is going to be True or False
  print('a =', a, '  b =', b, '  c =', c)
  return c == True

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(7)
```
</details>

In [ ]:
def sat(there: int):
  knock = 6
  whos = 3
  funny = (knock + knock != whos * there)
  return not funny  # I apologize again for my dads sense of humor

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(4)
```
</details>

In [ ]:
def sat(n: int):
  a = n > 50
  b = n < 50
  return not (a or b)

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(50)
```
</details>

In [ ]:
def sat(days: int):
  assert days > 7, 'more than one week'
  assert days < 10
  return days != 9

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(8)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(s: str):
  assert s + 'yo' == 'yo' + s
  assert len(s) > 5
  return True

sat(íäπ)

<details><summary>Answer</summary>

```python
sat('yoyo')
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  return n == n + 1 or n * 3 == 9

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(3)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  return n > 35 and n < 40

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(36)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  return n * n == 4 and n < 0

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(-2)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(i: int):
  ridiculous = (i > 35 and i < 17)
  common = (i > 100 or i < 100)
  return ridiculous or not common

sat(íäπ)

<details><summary>Answer</summary>




```python
sat(100)
```

</details>

# 5) üÜé types

Every python object has a type, like everyone has a blood type. Run these cells to figure out what python calls different objects. Read more about [types](https://cscircles.cemc.uwaterloo.ca/4-types/).

In [ ]:
type(17)  # find out what Python thinks the type of any object is

In [ ]:
type(12.5)  # did you know decimals *float* on water?

In [ ]:
type('unicorn')

In [ ]:
type('11')  # an integer or a string or both?

In [ ]:
type(['list', 'types'])  # you'll learn lists in the next notebook

In [ ]:
type(True)

In [ ]:

def sat(t: type):
  return t == type(2 + 2 == 5)

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(bool)
```
</details>

In [ ]:
def sat(b: bool):
  return b  # remember: you must make the function return `True`

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(True)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(b: bool):
  return type(b) == bool and b != True

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(False)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(b: bool):
  return b == (True or False)  # what's True or False?

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(True)
```

</details>

In [ ]:
######################## CHALLENGE ########################

def sat(b: bool):
  return b == (True and False)  # That doesn't make sense?

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(False)
```

</details>

In [ ]:
######################## CHALLENGE ########################

def sat(x: float):
  return x + 1 == 2 and type(x) == type(12.5)

<details><summary>Answer</summary>

```python
sat(1.0)
```
</details>

In [ ]:
type(sat) # what type is a puzzle?

You can convert objects from one type to another.

In [ ]:
str(True)

In [ ]:
1 + int('5')

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  return type(n) == int and len(str(n)) == 5

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(12345)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  return len(str(n - 1)) > len(str(n))

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(0)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  assert type(n) == int
  return bool(n) == False

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(0)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(s: str):
  assert type(s) == str
  return bool(s) == False

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(0)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  assert type(n) == int
  return len(str(n)) == 5

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(12345)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(n: int):
  assert type(n) == int
  return len(str(n)) == 5

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(12345)
```
</details>

In [ ]:
###########################################################
#                      EXTRA CREDIT                       #
###########################################################

def sat(t: type):
  return type(t) == t  # so meta!

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(type)
```

</details>

# 6) üòÜ *Fun*ctions

![image.png]()

A function takes input(s) and does something with them to produce output(s). Inputs are also called arguments. You've alread used built-in functions like `pow` and `len`, and each `sat` is a user-defined function. Have fun üòÜ with functions!

In [ ]:
# Review: a function of 2 variables

def sat(n: int):
  return pow(2, 2) == n

sat(íäπ)

In [ ]:
type(pow)  # check out its type

In [ ]:
# Review: a function of 1 variables

def sat(s: str):
  return len(s) == 5

sat(íäπ)

In [ ]:
type(len)  # what type is len?

In [ ]:
print("See the parentheses after print(...). That means it's also a function.")
print("print is an advanced function that takes any number of inputs!")
print("This example has", 3, 'inputs separated by 2 commas.')
print("Don't get confused by what's inside a string, 1 + 1 = ", 1 + 1)
print("Calling print with 0 inputs just prints a blank line:")
print()
print("print displays any number of things, but it has *no* output!")
what_does_it_return = print("In Python the special value `None` means nothing")
print("The value it returned was:", what_does_it_return)

In [ ]:
######################## CHALLENGE ########################

def lol(s: str):  # defines a new function!
  return s + "!"

def sat(s: str):
  return s == lol(lol(lol("haha")))  # uses it 3 times!!!

sat(íäπ)

In [ ]:
######################## CHALLENGE ########################

# you can define functions using other functions!

def lol(s: str):  # defines a new function!
  return s + "!"

def omg(s: str):
  wow = lol(lol(lol(s)))
  return wow + ' ' + wow + ' ' + wow

def sat(s: str):
  return omg(s) == "It's great!!! It's great!!! It's great!!!"

sat(íäπ)

In [ ]:
type(omg)  # check it out

In [ ]:
type(sat)  # sat is a function, too

In [ ]:
type(pow)  # not a user-defined function like omg/sat

In [ ]:
######################## CHALLENGE ########################

def f(n: int):
  return 'zero one two three four five six seven eight nine ten'.split()[n]

def g(n: int):
  return

def sat(c: str):
  return wrap(wrap(c + wrap(c) + c)) == "(-(-_(-_-)_-)-)"  # crowd pleaser

sat(íäπ)

In [ ]:
######################## CHALLENGE ########################

def wrap(s: str):
  return "(-" + s + "-)"

def sat(c: str):
  return wrap(wrap(c + wrap(c) + c)) == "(-(-_(-_-)_-)-)"  # crowd pleaser

sat(íäπ)

In [ ]:
######################## CHALLENGE ########################

def rep5(s: str):  # function names can have digits but can't start with a digit
  answer = s + s + s + s + s
  print("5 * ", s, "=", answer)
  return answer

def sat(s: str):
  return len(rep5(rep5(rep5(s)))) == 1000

sat(íäπ)

In [ ]:
######################## CHALLENGE ########################

def sat(s: str):
  return s == 'foo'
  return s == 'bar'
  print("Once the function returns, it exits and nothing after runs")
  print("This statement will never happen because it's after a return")
  assert 1 + 1 == 3, "Normally this would cause an error"
  x = 0 / 0  # also would cause an error
  sat(s)  # this would never end!

In [ ]:
######################## CHALLENGE ########################

# this is how a function of multiple variables is defined:

def cents(quarters: int, dimes: int, nickels: int, pennies: int):
  answer = 25 * quarters + 10 * dimes + 5 * nickels + pennies
  print(quarters, "quarters +", dimes, "dimes +", nickels, "nickels +", pennies, "pennies =", answer, "cents")
  return answer

def sat(d: int):
  return cents(3, d, 0, 4) == 99

# the order (3, d, 0, 4) when we call the cents function is matched with the
# order of the variables in the definition (quarters, dimes, nickels, pennies)
# to determine which variable gets which value

sat(íäπ)

In [ ]:
######################## CHALLENGE ########################

# this puzzle is still solvable even though the variable names don't match the

def cents(quarters: int, dimes: int, nickels: int, pennies: int):
  answer = 25 * pennies + 10 * nickels + 5 * dimes + quarters
  print(quarters, "quarters +", dimes, "dimes +", nickels, "nickels +", pennies, "pennies =", answer, "cents")
  return answer

def sat(d: int):
  return cents(3, d, 0, 4) == 99

# the order (3, d, 0, 4) when we call the cents function is matched with the
# order of the variables in the definition (quarters, dimes, nickels, pennies)
# to determine which variable gets which value

sat(íäπ)

In [ ]:
######################## CHALLENGE ########################

def cents(quarters: int, dimes: int, nickels: int, pennies: int):
  answer = 3 * dimes
  print("I'm returning 3 *", dimes, "=", answer, "just as I was told to do")
  return answer  # Python doesn't care what the variable names are

def sat(d: int):
  return cents(3, d, 0, 4) == 99

# Python does exactly as told, and does not care about what you meant or
# variable names

sat(íäπ)

In [ ]:
######################## CHALLENGE ########################

def cents(quarters: int, dimes: int, nickels: int, pennies: int):
  print("I'm returning 3 *", dimes, "=", 3 * dimes)  # Python lies if told to
  return 11 * dimes

def sat(d: int):
  return cents(3, d, 0, 4) == 99

sat(íäπ)

In [ ]:
######################## CHALLENGE ########################

def sat(q: int, d: int, n: int, p: int):
  return 25 * q + 10 * d + n * 5 + p == 99

sat(íäπ, íäπ, íäπ, íäπ)  # this sat has multiple arguments

In [ ]:
######################## CHALLENGE ########################

def fun(s: str):
  return íäπ + s  # replace íäπ with the right string to help define your first function

def sat():
  return fun('ny') == 'funny'

sat()  # () after sat is needed for Python to run the function with 0 inputs (try removing them)

In [ ]:
###########################################################
#                      EXTRA CREDIT                       #
###########################################################

# Functions *almost* always have parentheses after them

def compose(f, g, x):
  return f(g(x))

def sat(s: str):
  return compose(str, len, s) == '4'  # rarely will you see len without parentheses

sat(íäπ)

In [ ]:
###########################################################
#                      EXTRA CREDIT                       #
###########################################################

# In Python, functions are *first-class* objects and can be
# passed as inputs like numbers or strings!

def sat(f):
  return f('hello') == 5

sat(íäπ)

<details><summary>Answer and explanation</summary>

In this case, we are not actually running the length function.

```python
sat(len)
```

</details>

# üêõ Debug with ‚èÆ time-travel ‚è≠

Most programming time is actually spent fixing errors or **"debugging"**. [Grace Hopper](https://en.wikipedia.org/wiki/Grace_Hopper) famously wrote a program, and a moth got caught up in the circuitry and screwed it up. Now, that's a real bug! If you want to enjoy programming, try to enjoy your surprising and beautiful bugs! ü¶ã

Run the cell below to enable a **time-travel debugger** that allows you to step through a program  *forwards ‚è≠ and backwards* ‚èÆ!!!

In [ ]:
exec('# Run this cell to enable ‚èÆ time-travel ‚è≠ debugging. \ndef __enable_debugging__():  \n  import IPython\n  import urllib, datetime, re, sys\n  now = "\x1b[1;30m" + str(datetime.datetime.now()).split(".")[0] + " UTC\x1b[0m"\n\n  def post():\n    src = In[-1].strip().replace("íäπ", "CIRCLE")\n    if "__enable_debugging__" not in src:                  \n        height = 400 + src.count(chr(10))*22 + (100 if "print" in src else 0)\n        code=urllib.parse.quote(src)  \n        url=f"https://cscircles.cemc.uwaterloo.ca/visualize#code={code}&mode=display&raw_input=&curInstr=0"\n        onclick = f\'this.outerHTML = &#39;<iframe frameBorder=0 src="{url}" title="debug" width="100%" height="{height}px"></iframe>&#39;\'\n        html = f"<div onclick=\'{onclick}\' style=\'cursor:pointer;\'>‚èÆ‚è≠</div>"  \n        display(IPython.display.HTML(html))\n\n  e = get_ipython().events\n  e.callbacks[\'post_run_cell\'][:] = [f for f in e.callbacks[\'post_run_cell\'] if f.__name__ != \'post\'] + [post]\n  print("Debugger from https://cscircles.cemc.uwaterloo.ca and https://pythontutor.com enabled!")\n  print("Press ‚èÆ‚è≠ after a cell is run to step through its code.")\n  print("\t\t\t\t(Re-run this cell each time you restart the notebook.)")\n\n__enable_debugging__()')

In [ ]:
######################## CHALLENGE ########################

def sat(s: str):
  r = s[::-1]
  return 'Hello, ' + r == 'Hello, world!'

sat('world!')  # run the cell then step through with ‚èÆ‚è≠ to figure out what [::-1] does

# üößUNDER CONSTRUCTION üöß

From here on we're still working on the puzzles

# 7) üòØ `n = n + 1` !

In Python, `=` is different than `==`, and neither one is what you learned in math class. ü§™ Let's see the difference.

In [ ]:
print('Python code is evaluated in order, one step at a time')
x = 'im'  # x = (value) means set or change the value associated with variable x
print('The value of x is:', x)
x = 'possible'  # üôÄ that would not be okay in math class, im ‚â† possible
print('The value of x has been changed! It is now:', x)
print(x == 'possible') # == means "True/False, are they equal?"

In [ ]:
# Then run this cell and press ‚èØ which appears below it

def sat(s: str):
  a = 'im'
  a = 'possible'
  a == 'impossible'
  return s == a

sat('im')  # can you make it return True

In [ ]:
def sat(n: int):
  n = n + 10  # OMG, what does it mean? mathematically impossible!
  return n == 25

<details><summary>Answer and explanation</summary>

```python
sat(15)
```

In python, `n = n + 10` means "change" the value of `n` to it's old value plus 10.


</details>

In [ ]:
######################## CHALLENGE ########################

def sat(x):  # no type hint for x
  y = x + 3
  y = y * 2
  y = y + 7
  y = 'ok'
  return x == y

In [ ]:
######################## CHALLENGE ########################

def sat(x):
  x += ('i' * 2)
  x += ' is the best place ever!'
  return x == 'hawaii is the best place ever!'

In [ ]:
def sat(n: int):
  i = 1
  i = 2
  return n == i

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(2)
```
</details>

Yes, it's confusing!!! For more on how variables work, check out [CS circles: variables](https://cscircles.cemc.uwaterloo.ca/1-variables/).

In [ ]:
def sat(n: int):
  i = 2
  i = 'distracting fruit loops'
  i = 3
  i = i * i
  return n == i
  i = 17
  assert 2 + 'cat' == 1 / 0, "Normally this would cause an error, but..."
  print("this code never runs because it's after the return, try step-through")

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(9)
```
</details>

In [ ]:
def sat(n: int):
  a = 17
  b = a * 1234
  c = b - a
  d = c * a * b + 91257355253235000000000000000000000935023912357818579825
  return n == a * d

# Copying and getting the computer to do your work is not cheating!
a = 17
b = a * 1234
c = b - a
d = c * a * b + íäπ  # pro-tip: copy/paste saves mistakes!
n = íäπ * íäπ

sat(n)

<details><summary>Answer</summary>

```python
a = 17  
b = a * 1234
c = b - a
d = c * a * b + 91257355253235000000000000000000000935023912357818579825
n = a * d

sat(n)
```
</details>

In [ ]:
def sat(n: int):
  six = 1 + 1 + 1 + 1  # isn't this confusing?
  return n == 1 + six

sat(íäπ)

<details><summary>Answer</summary>

```python
sat(5)
````
</details>

**"Pythonic" variable names:** You can use any variable name you wish as long as it starts with a letter. Python doesn't care.
Programmers often use certain names for certain types of variables, like `i` or `n` for integers and `s` for strings. Even better, use *descriptive variable names* which tell other people (and your future self) what the variables mean, like `number_of_monkeys`. Lower-case variable names are recommended and since variable names cannot have spaces, you have to `use_underscores`.

In [ ]:
def penny_test(pennies: int):
  nickels = 1
  dimes = 1
  quarters = 3
  cents = 92
  return cents == quarters * 25 + dimes * 10 + nickels * 5 + pennies

penny_test(íäπ)

<details><summary>Answer</summary>

```python
penny_test(2)
````
</details>

## ‚òù String `'index'[4]`

In [ ]:
def sat(s: str):
  return s == 'dog'[0]

<details><summary>Answer</summary>

```python
sat('d')
```
</details>

In [ ]:
# This is not meant to offend any dog or cat lovers or imply that one is better
# than the other, but just so you know unicorns will always be superior
def sat(s: str):
  return s == 'cat'[1]

<details><summary>Answer</summary>

```python
sat('a')
```
</details>

In [ ]:
def sat(n: int):
  return 'unicorn'[n] == 'i'

<details><summary>Answer</summary>

```python
sat('2')
```
</details>

In [ ]:
def sat(s: str):
  return s[5] == 'f'

<details><summary>Answer</summary>

```python
sat('hellof')
```
</details>

In [ ]:
def sat(i: int):
  return 'unicorn'[i] == 'n' and i > 1

<details><summary>Hint</summary>

Remember `'unicorn'[0]` would be `'u'` and `i` must be more that 1. Also think about whether or not your solution should be a string.

</details>

<details><summary>Answer</summary>

```
sat(6)
```

</details>

In [ ]:
######################## CHALLENGE ########################

def sat(s: str):
  return s[3] + s[2] + s[1] + s[0] + s[2] + s[3] == 'evolve' and len(s) == 4

<details><summary>Answer</summary>

```python
sat('love')
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(s: str):
  return s[3] + 'yes' == 'eyes'

<details><summary>Answer</summary>

```python
sat('love')
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(s: str):
  return (len(s) == 3 or len(s) == 7) and s[5] == '!'

<details><summary>Answer</summary>

```python
sat('hello!!')
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(s: str):
  return len(s) == 4 and s.count('l') == 1 and s[2] == 'v'

<details><summary>Answer</summary>

```python
sat('love')
```
</details>

In [ ]:
###########################################################
#                      EXTRA CREDIT                       #
###########################################################

def sat(i: int):
  return 'unicorn'[i] == 'n' and i < 0  # negative index?!

<details><summary>Answer and explanation</summary>

```
sat(-1)
```

A negative index means that we count from the end of the string, with `s[-1]` being the last character of `s` and `s[-2]` being the second to last character,
and so forth.

</details>

<details><summary>Answer</summary>

```python
sat('')
```
</details>

# 8) ‚û° `if` and indentation

In [ ]:
def sat(n: int):
  if x > 5:
    return x < 8

<details><summary>Answer</summary>

```python
sat(7)
```
</details>

In [ ]:
def sat(n: int):
  if n > 6:
    return n < 2
  else:
    return n > 3

<details><summary>Answer</summary>

```python
sat(4)
```
</details>

In [ ]:
def sat(s: str):
  if s == 'unicorns are bad':
    return False
  else:
    return s == 'unicorns are great' or s == 'unicorns are awesome'

<details><summary>Answer</summary>

```python
sat('unicorns are awesome')
```
</details>

In [ ]:
def sat(s: str):
  a = s + 'ok'
  if a[1] != 'o':
    return False
  if a[0] != 'l':
    return False
  if len(a) != 4:
    return False
  return True

<details><summary>Answer</summary>

```python
sat('lo')
```
</details>

In [ ]:
def sat(n: int):
  if n > 17:
    return n < 5
  if n > 4:
    return n == 1
  else:
    return n == 2

<details><summary>Answer</summary>

```python
sat(2)
```
</details>

In [ ]:
def sat(n: int):
  if n > 5:
    return n == n + 1
  else:
    return n > 3

<details><summary>Answer</summary>

```python
sat(4)
```
</details>

In [ ]:
def sat(s: str):
  if s.count('good') == 1:
    if s.count('job!') == 1:
      return len(s) == 9
    else:
      return False
  return s.count('goodie') == 1

<details><summary>Answer</summary>

```python
sat('good job!')
```
</details>

# Section 5: Debugging & loops

In [ ]:
# TODO: move this to func section

len(str(pow(1234, 56789)))  # How many digits in big_num? (you'll learn str/len later)

In [ ]:
def sat(s: str):
  every_other = ""
  for i in range(7):
    j = 2 * i
    every_other = every_other + s[j]
  return every_other == 'unicorn'

In [ ]:
def sat(s: str):
  helper(1)
  every_other = ""
  helper(2)
  for i in range(7):
    helper(3)
    j = 2 * i
    helper(4)
    every_other = every_other + s[j]
  helper(5)
  return every_other == 'unicorn'

In [ ]:
sat('uanaiacaoarana')

In [ ]:
def sat(s: str):
  long_string = 'you should write a for loop for this puzzle! or you can do it by hand... fdgjdshgsuioerhg;oisehrg;oerihg;osdeihrgn;dlinjfgsdkxjfnviusedhngrviuserhgpouwseirhpoigsuhrngvo;isuehnvrtgo;iuwesnhrgbo;srduinhesiournhogaiesrhngv lisauedvgnhdkljbgnviu'
  length = len(long_string)
  every_other = ""
  for i in range(length):
    j = 2 * i
    every_other = every_other + s[j]
  return every_other == long_string

üëâ

In [ ]:
  def sat(s: str):
    long_string = 'you should write a for loop for this puzzle! or you can do it by hand... fdgjdshgsuioerhg;oisehrg;oerihg;osdeihrgn;dlinjfgsdkxjfnviusedhngrviuserhgpouwseirhpoigsuhrngvo;isuehnvrtgo;iuwesnhrgbo;srduinhesiournhogaiesrhngv lisauedvgnhdkljbgnviu'
    length = len(long_string)
>   every_other = ""
    for i in range(length):
      j = 2 * i
      every_other = every_other + s[j]
    return every_other == long_string

In [ ]:
def string_thing():
  long_string='you should write a for loop for this puzzle! or you can do it by hand... fdgjdshgsuioerhg;oisehrg;oerihg;osdeihrgn;dlinjfgsdkxjfnviusedhngrviuserhgpouwseirhpoigsuhrngvo;isuehnvrtgo;iuwesnhrgbo;srduinhesiournhogaiesrhngv lisauedvgnhdkljbgnviu'
  empty_string=""
  for i in range(241):
    empty_string+=long_string[i]+"l"
  return empty_string
sat(string_thing())

# Section 7: [lists, lists, ...]

## üìã Lists

In [ ]:
def sat(n: int):
  return [1, 5, n, 7] == [1, 5, 9, 7]

<details><summary>Answer</summary>

```python
sat(9)
```
</details>

In [ ]:
def sat(li: List[int]):
  return li + [4, 5, 6] == [1, 2, 3, 4, 5, 6]

<details><summary>Answer</summary>

```python
sat([1, 2, 3])
```
</details>

In [ ]:
def sat(s: str):
  li = ['unicorns', s, 'awesome']
  return li[1] == 'are'

<details><summary>Answer</summary>

```python
sat('are')
```
</details>

In [ ]:
def sat(n: int):
  return ['foo', 'bar', 'baz'][n] == 'baz'

<details><summary>Answer</summary>

```python
sat(2)
```
</details>

In [ ]:
def sat(li: list):
  fourth_item = li[3]
  return fourth_item == 'foobar'

<details><summary>Answer</summary>

```python
sat(['foo', 'bar', 'baz', 'foobar'])
```
</details>

In [ ]:
def sat(n: int):
  return ['cat'] * n == ['cat', 'cat', 'cat']

<details><summary>Answer</summary>

```python
sat(3)
```
</details>

In [ ]:
def sat(s: str):
  return ['cat', s] * 2 == ['cat', 'dog', 'cat', 'dog']

<details><summary>Answer</summary>

```python
sat('dog')
```
</details>

In [ ]:
def sat(li: list):
  return ['fun', 'knee'] * 2 == li

<details><summary>Answer</summary>

```python
sat(['fun', 'knee', 'fun', 'knee'])  # get it? not funny!
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(li: list):
  return li[100] == 'lion'

<details><summary>Sol___on</summary>

```python
sat([___] * ___)
```
</details>

<details><summary>Answer</summary>

```python
sat(['lion'] * 100)
```
</details>

In [ ]:
######################## CHALLENGE ########################

def sat(li: list):
  return len(li) == 5 and li.count('foo') == 3

In [ ]:
######################## CHALLENGE ########################

def sat(li: list):
  return (li + li).count('bar') == 4

In [ ]:
######################## CHALLENGE ########################

def sat(li: list):
  return li * li[1] == [3, 2, 1, 3, 2, 1]

In [ ]:
######################## CHALLENGE ########################

def sat(li: list):
  n = x[1]
  return x[n] > x[0]

In [ ]:
######################## CHALLENGE ########################

def sat(li: list):
  return x[x[1]] > x[0]

## üìãüìãüìã Lists of lists

In [ ]:
def sat(i):
  items = [['cat', 'unicorn'], ['apple', 'banana'], ['red', 'blue', 'green']]
  animals = items[0]
  print("Animals =", animals)
  ans = animals[i]
  print("Ans =", ans)
  return ans == 'unicorn'

In [ ]:
def sat(i):
  items = [['cat', 'unicorn'], ['apple', 'banana'], ['red', 'blue', 'green']]
  print("In the code below, first python evaluates items[i] =", items[i])
  print("Then it's 3rd item is extracted to get items[i][1] =", items[i][2])
  ans = items[i][2]
  return ans == 'green'

# Section 9: Loops

Let's start with `for ... in range(...)` loops.

## ‚û° Range loop: `for ... in range(...):`

In [ ]:
for i in range(3): # the 3 means the indendted stuff below, called the "body", will be run 3 times
  print('This statement is indented and executed on each run of the loop, which is called an iteration.')
print('This statement is NOT indented, so it is only executed after the loop finishes.')

In [ ]:
for i in range(3): # The variable i is changed on each iteration of the loop
  triclops = 3 * i
  print("i =", i, "and triclops =", triclops)
  print("All done!")  # This line was accidentally indented so it runs on each loop iteration. Oops. Python isn't intelligent. It does exactly what we say, not what we mean.

In [ ]:
for i in range(3): # The variable i is changed on each iteration of the loop
  triclops = 3 * i
  print("i =", i, "and triclops =", triclops)
print("All done!")

In [ ]:
def sat(x):
  total = 0
  for i in range(3):
    print('i is', i)
    total += i
  return total == x

In [ ]:
def solve4(x): # you can write your own loop to solve this one
  total = 0
  for i in range(100):
    total += i
  return total == x

In [ ]:
def sat(x):
  total = 0
  for i in range(100):
    total += i * i
  return total == x

In [ ]:
list(range(100)) # a range is kinda like a list, so for i in range(10)

In [ ]:
def sat(x):
  total = 0
  for i in range(100):
    if i < 10:
      total += i
    else:
      total += i * i
  return total == x

In [ ]:
def sat(x):
  total = 0
  for i in range(10):
    for j in range(10):
      print('i is', i, 'and j is', j)
      total += i * j
  return total == x

In [ ]:
def sat(x):
  total = 0
  for i in range(x):
    total += i
  return total == 55

In [ ]:
def sat(s: str):
  ss = ""
  for i in range(len(s)):
    ss = ss + s[i]
    ss = ss + s[i]
  return ss == 'uunniiccoorrnn'

In [ ]:
def sat(s: str):
  ss = ""
  for i in range(len(s)):
    ss = ss + s[i]
    ss = ss + s[i]
  return ss == 'uuuunnnniiiiccccoooorrrrnnnn'

In [ ]:
def sat(s: str):
  unicorn = ""
  amazing = ""
  alternating = True
  for i in range(len(s)):
    c = s[i]
    if alternating:
      unicorn = unicorn + c
    else:
      amazing = amazing + c
    print("c =", c, "| alternating =", alternating, "| unicorn =", unicorn, "| amazing =", amazing)
    alternating = not alternating
  return unicorn == 'unicorn' and amazing == 'amazing'

**TODO:** Teach range that starts with nonzero

In [ ]:
######################## CHALLENGE ########################

def sat(x):
  foo = ['hi', 'my', 'name', 'is', 'maya', 'and', 'I', 'love', 'unicorns', '!!!']
  n = len(foo)
  for i in range(n):
    s = foo[i]
    if len(s) == 3:
      return x == i

In [ ]:
######################## CHALLENGE ########################

def sat(x):
  total = 0
  for i in range(x):
    total += i * i
  return total == 612745

In [ ]:
######################## CHALLENGE ########################

def sat(x: str):
  for i in range(5):
    if x.count(x[i]) != i + 1:
      return False
  return True

In [ ]:
######################## CHALLENGE ########################

def sat(x: str):
  for i in range(100):
    if x.count(x[i]) < 100:
      return False
  return True

In [ ]:
######################## CHALLENGE ########################

def sat(x: str):
  for i in range(5):
    if x.count(x[i]) != i + 1:
      return False
  return True

In [ ]:
######################## CHALLENGE ########################

def sat(x: str):
  for i in range(100):
    if x.count(x[i]) < 100:
      return False
  return True

## ‚û∞ List loop: `for ... in [...]:`

`for` loops iterate over all elements of a list, or a string, or other `iterables` that you will learn about later

In [ ]:
# try me
for s in ['pizza', 'ramen', 'fruit']:
  print(s, 'is yummy')

In [ ]:
def sat(x):
  total = 0
  for i in [1, 3, 2]:
    total += i
    print('At this point, i =', i, 'and total =', total)
  return total == x

In [ ]:
def sat(x):
  total = 0
  for i in [1, 3, 2]:
    total += i
    print('At this point, i =', i, 'and total =', total)
  for i in [1, 3, 2]:
    total -= i
    print('At this point, i =', i, 'and total =', total)
  return total == x
sat(0)

In [ ]:
def sat(x):
  text = ''
  for s in ['loo', 'p o', 'ver st', 'rings']:
    text = text + s
    print('at this point s =', s, 'and text =', text)
  return text == x

In [ ]:
def solve1(x):
  text = ''
  for s in ['I lo', 'se', 'v', 'soo', 'e ', 'dump', 'string', 'lings!']:
    if s[0] != 's':
      text = text + s
    print('at this point s =', s, 'and text =', text)
  return text == x

In [ ]:
######################## CHALLENGE ########################

def sat(x):
  total = 0
  for i in [1, 2]:
    print('Looping over i =', i)
    for j in [3, 4]:
      print('   Looping over j =', j)
      total += i * j
  return x == total

In [ ]:
######################## CHALLENGE ########################

def sat(x): # How is this different than the previous puzzle
  total = 0
  for i in [1, 2]:
    print('Looping over i =', i)
  for j in [3, 4]:
    print('   Looping over j =', j)
    total += i * j
  return x == total

In [ ]:
def sat(x):
  # Hint: your answer x should be a long list of numbers. Use a loop to make it.
  n = 0
  print('Looping over your input x =', x)
  for i in x:
    n += 1
    print('Now, n =', n, 'and i =', i)
    if i != n:
      return False
  print('At the end, n =', n)
  return n == 100

## ‚û∞ String loop: `for ... in '...'`

In [ ]:
# try running this cell and see what happens
for character in 'happy yappy': # iterates over chars in the string, one by one
  print(character * 5)

In [ ]:
def solve2(x: str):   # : str is a 'type hint' telling you x should be a string
  for c in 'you can loop over a single string not just a list!':
    print('at this point, c = '' + c + '' and x = '' + x + ''')
    if c == x:
      return True

In [ ]:
def solve3(x: str):
  for c in 'this is a test':
    print('first loop: now c == '' + c + ''')
    if c == x:
      return False
  for c in 'this is another test':
    print('second loop: now c == '' + c + ''')
    if c == x:
      return True

## ‚ûø `while` loops

In [ ]:
def sat(x: int):
  i = 0
  while i != x:
    i = i + 1
  return i == 10

<details><summary>Answer</summary>

```python
sat()
```

</details>

In [ ]:
def sat(x: int):
  i = 0
  j = 0
  while i != x:
    i = i + 1
    j = j + 2
  return j == 10

<details><summary>Answer</summary>

```python
sat()
```

</details>

In [ ]:
def sat(x: int):
  s = ''
  while len(s) < 5:
    s = s + 'ha'
  return len(s) == x

<details><summary>Answer</summary>

```python
sat()
```

</details>

In [ ]:
######################## CHALLENGE ########################

def sat(x: str):
  s = ''
  while len(s) < 5:
    s += 'ha'
  return s == x

<details><summary>Answer</summary>

```python
sat('hahaha')
```

</details>

In [ ]:
######################## CHALLENGE ########################

def sat(x: list):  # x is a list of integers
  i = 0
  while x[i] != 1:
    i = x[i]
  return i == 100

<details><summary>Answer</summary>

```python
sat([100] * 100 + [1])
```

</details>

In [ ]:
###########################################################
#                      EXTRA CREDIT                       #
###########################################################

def sat(x: list):
  countdown = 100
  i = 0
  while x[i] != 0:
    i = x[i]
    countdown = countdown - 1
  return countdown == 0

<details><summary>Answer</summary>

```python
answer = []
for i in range(100):
  answer = answer + [i + 1]
answer = answer + [0]
sat(answer)
```

</details>

<details><summary>Shorter solution</summary>

```python
sat(list(range(1, 101))+[0])
```

</details>

# Section 9: **Fun**ctions

## Functions of a single variable

You've already been using functions. Every puzzle is a function. Now you are going to learn about defining new functions.

In [ ]:
def add_one(n):
  return n + 1

add_one(5) # guess what this will give

In [ ]:
def use_add_one(n: int):
  return add_one(n) == 5

<details><summary>Answer</summary>

```python
use_add_one(4)
```

</details>

In [ ]:
def add_twice(n: int):
  return add_one(add_one(n)) == 3

<details><summary>Answer</summary>

```python
add_twice(1)
```

</details>

In [ ]:
def sat(): # you have to define a function f!!!
  return f(1) == 4 and f(2) == 5

def f(n: int):
  return n + íäπ

sat()

<details><summary>Answer</summary>

```python
def f(x):
  x += 3
  return x
  
your_first_function(f)
```

</details>

In [ ]:
def sat():
  '''This function tests the `a` function.'''
  return a('twizzler') == 'a twizzler' and a('candy cane') == 'a candy cane'

def a(word: str):
  íäπ

sat()

<details><summary>Answer</summary>

```python
def a(word: str):
  return 'a ' + word

sat()
```

</details>

In [ ]:
def good_grammar():
  '''Tests an vs a on twizzler, apple, candy cane, and egg'''
  assert an('twizzler') == 'a twizzler'
  assert an('apple') == 'an apple'
  assert an('candy cane') == 'a candy cane'
  assert an('egg') == 'an egg'
  return True

def an(word: str):
  íäπ

sat()

<details><summary>Answer</summary>

```python
def an(x: str):
  if x == 'twizzler':
    return 'a twizzler'
  if x == 'apple':
    return 'an apple'
  if x == 'candy cane':
    return 'a candy cane'
  if x == 'egg':
    return 'an egg'

good_grammar(single)
```

</details>

In [ ]:
######################## CHALLENGE ########################

def sat():
  for word in ['twizzler', 'soda', 'burger', 'pizza']:
    assert singular(word) == 'a ' + word
  for word in ['apple', 'avocado', 'almond', 'artichoke']:
    assert singular(word) == 'an ' + word
  for word in ['egg', 'eggplant', 'edamame', 'enchilada']:
    assert singular(word) == 'an ' + word
  for word in ['ice cube', 'icky goo', 'ice cream cone']:
    assert singular(word) == 'an ' + word
  for word in ['olive', 'omelet', 'oreo']:
    assert singular(word) == 'an ' + word
  for word in ['umbrella', 'ugli fruit']:
    assert singular(word) == 'an ' + word
  return True

def singular(x: str):
  íäπ

sat()

<details><summary>Answer</summary>

```python
def singular(x: str):
  if x[0] == 'a' or x[0] == 'e' or x[0] == 'i' or x[0] == 'o' or x[0] == 'u':
    x = 'an ' + x
  else:
    x = 'a ' + x
  return x

sat(single)
```

</details>

<details><summary>Shorter solution</summary>

```python
def single(x):
  if 'aeiou'.count(x[0]) == 1:
    return 'an ' + x
  else:
    return 'a ' + x

better_grammar(single)
```

</details>

In [ ]:
######################## CHALLENGE ########################

def sat():
  for word in ['twizzler', 'soda', 'burger', 'unicorn']:
    assert single(word) == 'a ' + word
  for word in ['apple', 'avocado', 'almond', 'artichoke']:
    assert single(word) == 'an ' + word
  for word in ['egg', 'eggplant', 'edamame', 'enchilada']:
    assert single(word) == 'an ' + word
  for word in ['ice cube', 'icky goo', 'ice cream cone']:
    assert single(word) == 'an ' + word
  for word in ['olive', 'omelet', 'oreo']:
    assert single(word) == 'an ' + word
  for word in ['umbrella', 'ugli fruit']:
    assert single(word) == 'an ' + word
  return True

def singular(x: str):
  íäπ

sat()

<details><summary>Answer</summary>

```python
def singular(x: str):
  if x == 'unicorn':
    return 'a unicorn'
  else:
    return single(x)  # reuse previous solution (see last solution)

sat()
```

</details>

## Functions of more than one variable

In [ ]:
def sat(a, b):
  '''A function that takes two inputs'''
  return a == b + 1

sat(íäπ, íäπ)

<details><summary>Answer</summary>

```python
sat(17, 16)
```

</details>

In [ ]:
######################## CHALLENGE ########################

def sat(quarters, dimes, nickles, pennies):
  test_change(74, quarters, dimes, nickles, pennies)
  return True

def test_change(cents, quarters, dimes, nickels, pennies):
  assert type(quarters) == type(dimes) == type(nickels) == type(pennies) == int
  assert 0 <= quarters
  assert 0 <= dimes < 3
  assert 0 <= nickels < 2
  assert 0 <= pennies < 5
  assert cents == quarters * 25 + dimes * 10 + nickels * 5 + pennies

sat(íäπ, íäπ, íäπ, íäπ)

<details><summary>Answer</summary>

```python
sat(2, 2, 0, 4)
```

</details>

In [ ]:
######################## CHALLENGE ########################

def sat():
  for cents in range(100):
    change = make_change(cents)
    [quarters, dimes, nickels, pennies] = change  # *see explanation below
    test_change(cents, quarters, dimes, nickels, pennies)
  return True

def make_change(cents: int):
  quarters = cents // 25  #  // is "integer division" (computes quotient)
  íäπ # compute dimes, nickels and pennies
  return [quarters, dimes, nickels, pennies]

sat()

<details><summary>Answer</summary>

```python
def make_change(cents: int):
  quarters = cents // 25  #  // does "integer division" (computes quotient)
  cents -= quarters * 25
  dimes = cents // 10
  cents -= dimes * 10
  nickels = cents // 5
  cents -= nickels * 5
  pennies = cents
  return [quarters, dimes, nickels, pennies]

sat()
```
</details>

*Python offers some nice shortcuts. For example, the following code:

```python
[quarters, dimes, nickels, pennies] = make_change(cents) # [shortcut]
```

is a shortcut for:

```python
change   = make_change(cents)
assert len(change) == 4
quarters = change[0]
dimes    = change[1]
nickels  = change[2]
pennies  = change[3]
```

and you don't even need the `[]`:

```python
quarters, dimes, nickels, pennies = make_change(cents) # shortcut
```

As we will learn later, just when you thought it couldn't get any shorter, the entire thing can be written as:

```python
test_change(cents, *make_change(cents))  # *wow!!!
```

The `*` here unpacks the list returned by `make_change` and passes them in order as arguments to `test_change`. ü§Ø

In [ ]:
def sat(n: int):
  for i in range(100):
    if i % 2 == 0:
      continue
    n -= i
  return n == 0

sat(2500)

In [ ]:
def sat(s: str):
  sentence = 0
  consonants = 0
  for c in s:
    sentence = sentence + 1
    if c in "aeiouy":
      continue
    consonants = consonants + 1
    if c == ".":
      break
  return consonants == 3 and sentence == 5 and len(s) == 7


sat("dfaa.ef")

# Debugging

In [ ]:
# Run this to enable debugging. We don't expect you to understand it!
def __enable_debugging__():
  import IPython
  import urllib, datetime, re, sys
  now = "\033[1;30m" + str(datetime.datetime.now()).split(".")[0] + " UTC\033[0m"

  def post():
    src = In[-1].strip().replace("íäπ", "CIRCLE")
    if "__enable_debugging__" not in src:
        height = 400 + src.count("\n")*22 + (100 if "print" in src else 0)
        code=urllib.parse.quote(src)
        url=f"https://cscircles.cemc.uwaterloo.ca/visualize#code={code}&mode=display&raw_input=&curInstr=0"
        onclick = f'this.outerHTML = &#39;<iframe frameBorder=0 src="{url}" title="debug" width="100%" height="{height}px"></iframe>&#39;'
        html = f"<a onclick='{onclick}' style='cursor:pointer;'>‚èØ</a>"
        display(IPython.display.HTML(html))

  e = get_ipython().events
  e.callbacks['post_run_cell'][:] = [f for f in e.callbacks['post_run_cell'] if f.__name__ != 'post'] + [post]
  print("You will have to re-run this every time you restart this notebook.")
  print("This loads a step-by-step debugger from https://cscircles.cemc.uwaterloo.ca and https://pythontutor.com")

__enable_debugging__()

In [ ]:
1

In [ ]:
1